services:
  jmeter:
    build:
      context: .
      args:
        JMETER_VERSION: "5.6.3"
    container_name: jmeter-cli
    environment:
      threads: "50"
      rampup: "10"
      duration: "60"
      JMETER_HEAP: "-Xms512m -Xmx2048m"
      JMETER_TESTPLAN: "/testplan/load-test-1.jmx"
      JMETER_JTL: "/results/results.jtl"
      JMETER_REPORT: "/reports/html"
    volumes:
      - /var/snap/amazon-ssm-agent/11797/jmeter-docker/testplan:/testplan:ro
      - /var/snap/amazon-ssm-agent/11797/jmeter-docker/config:/config:ro
      - /var/snap/amazon-ssm-agent/11797/jmeter-docker/results:/results
      - /var/snap/amazon-ssm-agent/11797/jmeter-docker/reports:/reports

  report-server:
    image: nginx:stable-alpine
    depends_on:
      - jmeter
    volumes:
      - /var/snap/amazon-ssm-agent/11797/jmeter-docker/reports/html:/usr/share/nginx/html:ro
    ports:
      - "8080:80"